{
 "title": "Heart Disease API Overview",
 "tags": [
  "prometheus",
  "fastapi",
  "ml"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Predictions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(predictions_total)" }
   ]
  },
  {
   "title": "Active Predictions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_predictions" }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(prediction_errors_total)" }
   ]
  },
  {
   "title": "Avg Execution Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(prediction_duration_seconds_sum[5m])) / sum(rate(prediction_duration_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Prediction Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prediction_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Predictions Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(predictions_total[5m])) by (endpoint)"
    }
   ]
  }
 ]
}